# Permalinks
permalink:           pretty

# Setup
title:               'Alex Hay'
url:                 https://alexhay.dev
tagline:             Indie app developer
paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""

# Includes
include:
  - _redirects
  
collections:
  category:
    output: true

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alex Hay
  url:               https://twitter.com/mralexhay
  email:             mralexhay@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/bradleytaunt/taunt-jekyll

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
